### PR TITLE
fix(paginator): using keyword-flag to persist pagination results

### LINKED ISSUE #314: Bug: page selector of search results makes wrong request
**Describe the bug**
 
When the user is browsing "Keyword" search results and clicks on the arrows at the bottom of the screen to navigate to previous/next pages, the request sent to the API is incorrect. 

When the user clicks on the "search" button the request submitted to the REST API is:

`GET  https://mylibrary.aiod.eu/api-metadata/v2/search/datasets?page=0&limit=15&search_query=climate change`

which is correct. However, when she clicks on the right-arrow to navigate to the second page of results the request submitted to the REST API is the one to obtain assets, not to the "/search" enpdont: 

`GET
	https://mylibrary.aiod.eu/api-metadata/v2/datasets?schema=aiod&offset=15&limit=15&sort=date_modified&direction=desc`

**To Reproduce**
* Select asset type "Datasets" because it is more likely to have more than 15 search results. 
* Search text "climate change", with the "Keyword" mode activated.
Image

* Click on the right arrow at the bottom part of the screen to navigate to page 2 and inspect HTTP requests in the web browser dev tools (section  "Network").

Image

* You can also notice that the results title and description do not match the search query.

**Expected behavior**
When the user clicks on the arrows after performing a "Keyword" search, the requests to be submiitted should be of the form:

`GET  https://mylibrary.aiod.eu/api-metadata/v2/search/datasets?page=X&limit=Y&search_query=climate change`

where X and Y must be the corresponding page and limit values. 

**IMPORTANT NOTES**
* This fix must be applied only to the "keyword search". Requests for the  "AI Mode" search (the one that relies on RAIL's URL)  must be the same.
* Note that the parameters of the query for the "keyword" search must be updated. Currently we have something of the style: 
GET  https://mylibrary.aiod.eu/api-metadata/v2/search/datasets?page=0&limit=15&search_query=climate change

but parameter "page" does not exist anymore. Instead, we must use "offset". Ex: 

   * First request is something of the form: /search/datasets?search_query=climate change&exact_match=false&sort_by_id=false&limit=15&**offset=0**&get_all=false

   * And request clicking on the right arrow should be: /search/datasets?search_query=climate change&exact_match=false&sort_by_id=false&limit=15&**offset=15**&get_all=false

### PR DESCRIPTION
**Pull request by andresvicentehector**
## Change

Fixed pagination behavior in assets-list when keyword search is active.
Updated goToPage and onPageSizeChange so they call keyword search (basicSearch) instead of generic asset listing when a search query exists.
Added pagination bounds validation in goToPage to avoid invalid page requests.
Added a small helper to detect active keyword search reliably from component/filter state.

## How to Test

Go to assets list.
Ensure Keyword mode is active (not AI mode).
Enter a query (e.g. climate change) and click Search.
Move to the next page using paginator arrows.
Verify the request keeps hitting search endpoint with updated page and same search_query/limit (e.g. .../search/datasets?offset=1&limit=15&search_query=climate%20change).
Change items per page and verify results reload from page 0 using the same keyword query.
Clear the search input and verify pagination goes back to normal assets listing flow.

## Checklist
- [ ] Tests have been added or updated to reflect the changes, or their absence is explicitly explained.
- [ ] Documentation has been added or updated to reflect the changes, or their absence is explicitly explained.
- [ ] A self-review has been conducted checking:
  - No unintended changes have been committed.
  - The changes in isolation seem reasonable.
  - Anything that may be odd or unintuitive is provided with a GitHub comment explaining it (but consider if this should not be a code comment or in the documentation instead).
- [ ] All CI checks pass before pinging a reviewer, or provide an explanation if they do not.

## Related Issues

Closes #314

### CODE REVIEW

File: src/app/modules/marketplace/components/assets-list/assets-list.component.ts [hunk 1]
```diff
@@ -679,24 +667,38 @@ export class AssetsListComponent implements OnInit, OnDestroy {
     this.currentPage = 0;
     this.offset = 0;
 
-    if (!this.isEnhancedSearch) {
+    if (!this.isEnhancedSearch && this.isKeywordSearchActive()) {
```
Comment (soniasantiago) [inline src/app/modules/marketplace/components/assets-list/assets-list.component.ts]: New lines 670 to 676 are exactly the same as lines 686 to 692, so you can extract that code to a function, and replace the current code by a call to that function in both places.

**Review by soniasantiago — CHANGES_REQUESTED** [review]
Change destination branch to `staging` instead of `main`
