### PR TITLE
fix(top-navbar): adding contribute button to top-navbar

### LINKED ISSUE #132: Integration with MCE?
_[Needs more definition]_

It might be necessary to include some integration with the Metadata Catalogue Editor. For instance, including a link to the form  in the MCE to create a new asset of a certain type. But there are not more details at this moment.

### PR DESCRIPTION
**Pull request by andresvicentehector**
## Change

Add mceUrl to both dev and prod environment configs so the correct MCE endpoint comes from runtime env vars.
Update TopNavbarComponent.onClickContribute to redirect using environment.mceUrl instead of a hard-coded URL.

## How to Test

Log in, open the top navbar, click “Contribute”, and verify the redirect goes to the environment-specific URL.

## Checklist
- [ ] Tests have been added or updated to reflect the changes, or their absence is explicitly explained.
- [ ] Documentation has been added or updated to reflect the changes, or their absence is explicitly explained.
- [x] A self-review has been conducted checking:
  - No unintended changes have been committed.
  - The changes in isolation seem reasonable.
  - Anything that may be odd or unintuitive is provided with a GitHub comment explaining it (but consider if this should not be a code comment or in the documentation instead).
- [ ] All CI checks pass before pinging a reviewer, or provide an explanation if they do not.

## Related Issues

closes #132

### CODE REVIEW

File: src/environments/environment.development.ts [hunk 1]
```diff
@@ -27,4 +27,7 @@ export const environment = {
   zohoConfig: {
     base: '',
   },
+  MCEConfig: {
+    mceUrl: browserwindow.env?.['MCE_URL_DEV'] || '',
```
Comment (soniasantiago) [inline src/environments/environment.development.ts]: Use variable name finally used in .env (ex: 'MCE_URL')

File: src/environments/environment.production.ts [hunk 2]
```diff
@@ -26,4 +26,7 @@ export const environment = {
   zohoConfig: {
     base: browserwindow.env?.['ZOHO_URL'] || '',
   },
+  MCEConfig: {
+    mceUrl: browserwindow.env?.['MCE_URL_PROD'] || 'https://editor.aiod.eu/',
```
Comment (soniasantiago) [inline src/environments/environment.production.ts]: Use variable name finally used in .env (ex: 'MCE_URL')

**Review by soniasantiago — APPROVED** [review]
